stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - projeet
  script:
    - echo "Build du projet"

test-job:
  stage: test
  tags:
    - projeet
  script:
    - echo "Tests en cours"

deploy-job:
  stage: deploy
  tags:
    - projeet
  script:
    - echo "Deploiement"